# Generated by Django 5.1.3 on 2024-11-29 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 20, 43, 31, 678385, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicacion'),
        ),
    ]
